data:
  root_path: "/content/drive/MyDrive/ANDREW/ANDREW/manifest-1754856038374/NSCLC Radiogenomics"
  metadata_csv: "/content/drive/MyDrive/ANDREW/ANDREW/manifest-1754856038374/metadata.csv"
  clinical_csv: "/content/drive/MyDrive/ANDREW/ANDREW/manifest-1754856038374/NSCLCR01Radiogenomic_DATA_LABELS_2018-05-22_1500-shifted.csv"
  image_size: [64, 64, 32]
  batch_size: 1
  num_workers: 0
  pin_memory: false

model:
  architecture: "multimodal_resnet3d"
  num_classes: 2
  hidden_dim: 512
  dropout: 0.3

training:
  epochs: 2
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  save_every: 5
  checkpoint_dir: "/content/drive/MyDrive/checkpoints"
